export const RoleDataList: string[] = [
    
    'Dashboard',
    'Mes Bulletins',
    'Personnels',
    'Pointages', 
    'Registre de presences', 
    'Heure suplementaires',
    'Liste de paiements', 
    'Statuts de paies',
    'Relevés de paies',
    'Avances salaires',
    'Primes divers',
    'Pénalites',
    'Pret entreprise',
    'Indemnités',
    'Syndicats', 
    'Horaires', 
    'Performences', 
    'Postes',
    'Candidatures',
    'Emails',
    'Preferences',
    'Reglages',
    'Entreprises',
    'Departements',
    'Sites location',
    'Fonctions', 
    'Services',
    'Titres',
    'Archives',
  ]

  export const RoleSupportDataList: string[] = [
    'Dashboard',
    'Mes Bulletins',
    'Personnels', 
    'Pointages', 
    'Registre de presences', 
    'Heure suplementaires',
    'Liste de paiements', 
    'Statuts de paies',
    'Relevés de paies',
    'Avances salaires',
    'Primes divers',
    'Pénalites',
    'Pret entreprise',
    'Indemnités',
    'Syndicats', 
    'Horaires', 
    'Performences', 
    'Postes',
    'Candidatures',
    'Emails',
    'Preferences',
    'Reglages',
    'Entreprises',
    'Departements',
    'Sites location',
    'Fonctions', 
    'Services',
    'Titres',
    'Archives',
    'Support',
  ]